### ISSUE TITLE
mongodb not mentioned in the requirements

### ISSUE THREAD

**Issue by Euphorbium** [joaoqalves/web2py-oauth2#7]
Is it possible to run this without mongodb? Documentation does not mention that mongodb is required, but various imports fail without mongodb related modules installed in  the system.

**Comment by joaoqalves** [comment]
Hi @Euphorbium. This project was built to work under MongoDB. There's a @SamuelMarks fork that uses Web2Py DAL instead of MongoDB. We did not update the README file. I'm sorry :)
